config_file : './tutorial_exps/config.py'
ann_file_test : 'data/kinetics400_tiny/kinetics_tiny_val_video.txt'
data_prefix_video_test: 'data/kinetics400_tiny/val'
checkpoint_file : './tutorial_exps/best_acc_top1_epoch_2.pth'